######################################################################
# Automatically generated by qmake (3.0) jue abr 3 13:35:44 2014
######################################################################

TEMPLATE = app
TARGET = graph
INCLUDEPATH += .
QT += xml

# Input
HEADERS += Iterable.hpp Node.hpp Graph.hpp SerializableGraph.hpp
SOURCES += test.cpp
