######################################################################
# Automatically generated by qmake (3.0) sáb abr 5 11:24:52 2014
######################################################################

TEMPLATE = app
TARGET = graphicalItems
INCLUDEPATH += .
QT += quick qml widgets

# Input
HEADERS += GraphicalNode.hpp \
	GraphicalNodesManager.hpp\
	FloatingMenu.hpp
SOURCES += GraphicalNode.cpp\
	GraphicalNodesManager.cpp\ 
	FloatingMenu.cpp \
	main.cpp
