######################################################################
# Automatically generated by qmake (3.0) s�b abr 5 11:24:52 2014
######################################################################

TEMPLATE = app
TARGET = graphicalItems
INCLUDEPATH += .
QT += quick qml widgets

# Input
HEADERS += GraphicalNode.hpp \
	GraphicalNodesManager.hpp\
	FloatingMenu.hpp
SOURCES += GraphicalNode.cpp\
	GraphicalNodesManager.cpp\ 
	FloatingMenu.cpp \
	main.cpp

OTHER_FILES += \
    ../qml/ActionIndicatorQML.qml \
    ../qml/Button.qml \
    ../qml/FloatingMenuQML.qml \
    ../qml/GraphicalNode.qml \
    ../qml/MainWindow.qml \
    ../qml/PaperSheet.qml \
    ../qml/ScrollBar.qml
